    - name: RSI Diff Bot
                uses: mirrorcult/RSIDiffBot@v1.1
            

      - name: Update comment to read that it has been edited
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: append
          body: |
            Edit: diff updated after ${{ github.event.pull_request.head.sha }}
